services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_local_data:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
    restart: unless-stopped

volumes:
  dynamodb_local_data:
